#Message is encoded with a simple shift cipher (caesar cipher)
#All punctuation and spaces are removed.  All letters are uppercase.
message = "BRKYVIZEV AFYEJFE SZFXIRGYP. SZFXIRGYP SP DRIXFK CVV JYVKKVICP. SVZEX YREUGZTBVU KF SV FEV FW KYIVV SCRTB JKLUVEKJ KF ZEKVXIRKV NVJK MZIXZEZR’J XIRULRKV JTYFFCJ ZJ JFDVKYZEX KYRK DREP GVFGCV NFLCU TFEJZUVI FEV FW KYVZI CZWV’J DFJK EFKRSCV DFDVEKJ, SLK ZK’J ALJK FEV FW JVMVIRC SIVRBKYIFLXYJ KYRK YRMV DRIBVU BRKYVIZEV AFYEJFE’J CFEX REU IVDRIBRSCV CZWV. SFIE ZE NYZKV JLCGYLI JGIZEXJ, NVJK MZIXZEZR, ZE 1918, YVI ZEKVEJV TLIZFJZKP REU SIZCCZRETV NZKY ELDSVIJ MRLCKVU YVI RYVRU JVMVIRC XIRUVJ ZE JTYFFC. SP 13, JYV NRJ RKKVEUZEX KYV YZXY JTYFFC FE KYV TRDGLJ FW YZJKFIZTRCCP SCRTB NVJK MZIXZEZR JKRKV TFCCVXV. RK 18, JYV VEIFCCVU ZE KYV TFCCVXV ZKJVCW, NYVIV JYV DRUV HLZTB NFIB FW KYV JTYFFC’J DRKY TLIIZTLCLD REU WFLEU R DVEKFI ZE DRKY GIFWVJJFI N. N. JTYZVWWVCZE TCRPKFI, KYV KYZIU RWIZTRE RDVIZTRE KF VRIE R GYU ZE DRKYVDRKZTJ. JYV XIRULRKVU NZKY YZXYVJK YFEFIJ ZE 1937 REU KFFB R AFS KVRTYZEX RK R SCRTB GLSCZT JTYFFC ZE MZIXZEZR. NYVE NVJK MZIXZEZR UVTZUVU KF HLZVKCP ZEKVXIRKV ZKJ XIRULRKV JTYFFCJ ZE 1939, NVJK MZIXZEZR JKRKV’J GIVJZUVEK, UI. AFYE N. URMZJ, JVCVTKVU YVI REU KNF DVE KF SV KYV WZIJK SCRTB JKLUVEKJ FWWVIVU JGFKJ RK KYV JKRKV’J WCRXJYZG JTYFFC, NVJK MZIXZEZR LEZMVIJZKP. JYV CVWK YVI KVRTYZEX AFS REU VEIFCCVU ZE KYV XIRULRKV DRKY GIFXIRD. RK KYV VEU FW KYV WZIJK JVJJZFE, YFNVMVI, JYV UVTZUVU KF CVRMV JTYFFC KF JKRIK R WRDZCP NZKY YVI WZIJK YLJSREU, ARDVJ XFSCV.  JYV IVKLIEVU KF KVRTYZEX NYVE YVI KYIVV URLXYKVIJ XFK FCUVI, SLK ZK NRJE’K LEKZC 1952 KYRK R IVCRKZMV KFCU YVI RSFLK FGVE GFJZKZFEJ RK KYV RCC-SCRTB NVJK RIVR TFDGLKZEX JVTKZFE RK KYV ERKZFERC RUMZJFIP TFDDZKKVV WFI RVIFERLKZTJ’ (ERTR’J) CREXCVP CRSFIRKFIP, YVRUVU SP WVCCFN NVJK MZIXZEZRE UFIFKYP MRLXYRE. BRKYVIZEV REU YVI YLJSREU UVTZUVU KF DFMV KYV WRDZCP KF EVNGFIK EVNJ, MZIXZEZR, KF GLIJLV KYV FGGFIKLEZKP, REU BRKYVIZEV SVXRE NFIB RK CREXCVP ZE KYV JLDDVI FW 1953. ALJK KNF NVVBJ ZEKF YVI KVELIV ZE KYV FWWZTV, UFIFKYP MRLXYRE RJJZXEVU YVI KF R GIFAVTK ZE KYV DREVLMVI CFRUJ SIRETY FW KYV WCZXYK IVJVRITY UZMZJZFE, REU BRKYVIZEV’J KVDGFIRIP GFJZKZFE JFFE SVTRDV GVIDREVEK. JYV JGVEK KYV EVOK WFLI PVRIJ RERCPQZEX URKR WIFD WCZXYK KVJKJ REU NFIBVU FE KYV ZEMVJKZXRKZFE FW R GCREV TIRJY TRLJVU SP NRBV KLISLCVETV. RJ JYV NRJ NIRGGZEX LG KYZJ NFIB YVI YLJSREU UZVU FW TRETVI ZE UVTVDSVI 1956. KYV 1957 CRLETY FW KYV JFMZVK JRKVCCZKV JGLKEZB TYREXVU YZJKFIP—REU AFYEJFE’J CZWV. ZE 1957, JYV GIFMZUVU JFDV FW KYV DRKY WFI KYV 1958 UFTLDVEK EFKVJ FE JGRTV KVTYEFCFXP, R TFDGVEUZLD FW R JVIZVJ FW 1958 CVTKLIVJ XZMVE SP VEXZEVVIJ ZE KYV WCZXYK IVJVRITY UZMZJZFE REU KYV GZCFKCVJJ RZITIRWK IVJVRITY UZMZJZFE (GRIU). VEXZEVVIJ WIFD KYFJV XIFLGJ WFIDVU KYV TFIV FW KYV JGRTV KRJB XIFLG, KYV ERTR’J WZIJK FWWZTZRC WFIRP ZEKF JGRTV KIRMVC. AFYEJFE, NYF YRU NFIBVU NZKY DREP FW KYVD JZETV TFDZEX KF CREXCVP, “TRDV RCFEX NZKY KYV GIFXIRD” RJ KYV ERTR SVTRDV ERJR CRKVI KYRK PVRI. JYV UZU KIRAVTKFIP RERCPJZJ WFI RCRE JYVGRIU’J DRP 1961 DZJJZFE WIVVUFD 7, RDVIZTR’J WZIJK YLDRE JGRTVWCZXYK. ZE 1960, JYV REU VEXZEVVI KVU JBFGZEJBZ TFRLKYFIVU UVKVIDZERKZFE FW RQZDLKY REXCV RK SLIEFLK WFI GCRTZEX R JRKVCCZKV FMVI R JVCVTKVU VRIKY GFJZKZFE, R IVGFIK CRPZEX FLK KYV VHLRKZFEJ UVJTIZSZEX RE FISZKRC JGRTVWCZXYK ZE NYZTY KYV CREUZEX GFJZKZFE FW KYV JGRTVTIRWK ZJ JGVTZWZVU. ZK NRJ KYV WZIJK KZDV R NFDRE ZE KYV WCZXYK IVJVRITY UZMZJZFE YRU IVTVZMVU TIVUZK RJ RE RLKYFI FW R IVJVRITY IVGFIK. ZE 1962, RJ ERJR GIVGRIVU WFI KYV FISZKRC DZJJZFE FW AFYE XCVEE, AFYEJFE NRJ TRCCVU LGFE KF UF KYV NFIB KYRK JYV NFLCU SVTFDV DFJK BEFNE WFI. KYV TFDGCVOZKP FW KYV FISZKRC WCZXYK YRU IVHLZIVU KYV TFEJKILTKZFE FW R NFICUNZUV TFDDLEZTRKZFEJ EVKNFIB, CZEBZEX KIRTBZEX JKRKZFEJ RIFLEU KYV NFICU KF ZSD TFDGLKVIJ ZE NRJYZEXKFE, TRGV TRERMVIRC ZE WCFIZUR, REU SVIDLUR. KYV TFDGLKVIJ YRU SVVE GIFXIRDDVU NZKY KYV FISZKRC VHLRKZFEJ KYRK NFLCU TFEKIFC KYV KIRAVTKFIP FW KYV TRGJLCV ZE XCVEE’J WIZVEUJYZG 7 DZJJZFE WIFD CZWKFWW KF JGCRJYUFNE, SLK KYV RJKIFERLKJ NVIV NRIP FW GLKKZEX KYVZI CZMVJ ZE KYV TRIV FW KYV VCVTKIFEZT TRCTLCRKZEX DRTYZEVJ, NYZTY NVIV GIFEV KF YZTTLGJ REU SCRTBFLKJ. RJ R GRIK FW KYV GIVWCZXYK TYVTBCZJK, XCVEE RJBVU VEXZEVVIJ KF “XVK KYV XZIC”—AFYEJFE—KF ILE KYV JRDV ELDSVIJ KYIFLXY KYV JRDV VHLRKZFEJ KYRK YRU SVVE GIFXIRDDVU ZEKF KYV TFDGLKVI, SLK SP YREU, FE YVI UVJBKFG DVTYREZTRC TRCTLCRKZEX DRTYZEV.  “ZW JYV JRPJ KYVP’IV XFFU,’” BRKYVIZEV AFYEJFE IVDVDSVIJ KYV RJKIFERLK JRPZEX, “KYVE Z’D IVRUP KF XF.” XCVEE’J WCZXYK NRJ R JLTTVJJ, REU DRIBVU R KLIEZEX GFZEK ZE KYV TFDGVKZKZFE SVKNVVE KYV LEZKVU JKRKVJ REU KYV JFMZVK LEZFE ZE JGRTV. NYVE RJBVU KF ERDV YVI XIVRKVJK TFEKIZSLKZFE KF JGRTV VOGCFIRKZFE, AFYEJFE NFLCU KRCB RSFLK KYV TRCTLCRKZFEJ KYRK YVCGVU JPETY GIFAVTK RGFCCF’J CLERI DFULCV NZKY KYV CLERI-FISZKZEX TFDDREU REU JVIMZTV DFULCV. JYV RCJF NFIBVU FE KYV JGRTV JYLKKCV REU KYV VRIKY IVJFLITVJ KVTYEFCFXP JRKVCCZKV (VIKJ, CRKVI IVERDVU CREUJRK) REU RLKYFIVU FI TFRLKYFIVU 26 IVJVRITY IVGFIKJ. JYV IVKZIVU ZE 1986, RWKVI 33 PVRIJ RK CREXCVP. “Z CFMVU XFZEX KF NFIB VMVIP JZEXCV URP,” JYV JRZU. ZE 2015, RK RXV 97, AFYEJFE RUUVU REFKYVI VOKIRFIUZERIP RTYZVMVDVEK KF YVI CFEX CZJK: GIVJZUVEK SRIRTB FSRDR RNRIUVU YVI KYV GIVJZUVEKZRC DVURC FW WIVVUFD, RDVIZTR’J YZXYVJK TZMZCZRE YFEFI. JYV UZVU FE WVS. 24, 2020. ERJR RUDZEZJKIRKFI ARDVJ SIZUVEJKZEV JRZU, 'FLI ERJR WRDZCP ZJ JRU KF CVRIE KYV EVNJ KYRK BRKYVIZEV AFYEJFE GRJJVU RNRP KYZJ DFIEZEX RK 101 PVRIJ FCU. JYV NRJ RE RDVIZTRE YVIF REU YVI GZFEVVIZEX CVXRTP NZCC EVMVI SV WFIXFKKVE.'"

def decode(message):
  #initialize several variables for use in the function
  alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  solved = False
  shift = 0

  #start looping until the message has been decoded
  while not solved:
    #setup a holder variable
    result = ""
    #loop through each letter in the message
    for letter in message:
      if letter in alphabet:
        #get the new letter and add it to the result
        letter_index = alphabet.index(letter)
        new_letter = alphabet[(letter_index+shift)%26]
        result = result + new_letter
      else:
        result = result + letter
    #print out the results
    print(result)
    print(shift)

    #check if the message has been decoded
    if input("Message Solved? ").upper() == "Y":
        solved = True
    else:
        shift += 1
      
decode(message)